"""paket 6 minggu

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 09:24:40.673914
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blind_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wells", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("blind_set_id", sa.Integer(), nullable=True),
        sa.Column("wells", sa.JSON(), nullable=False),
        sa.Column("excluded", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("n_rows", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blind_set_id"],
            ["blind_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=True),
        sa.Column("section_in", sa.Float(), nullable=True),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("value_si", sa.Float(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["well_id"], ["wells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quality_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reviewer", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["well_id"], ["wells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_reviews_well_id"), "quality_reviews", ["well_id"], unique=False
    )
    op.create_table(
        "well_quality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=1), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["well_id"], ["wells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("well_id"),
    )
    op.create_table(
        "prediction_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["well_id"], ["wells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_evaluations_well_id"),
        "prediction_evaluations",
        ["well_id"],
        unique=False,
    )
    op.add_column("models", sa.Column("dataset_id", sa.Integer(), nullable=True))
    op.add_column("models", sa.Column("comparison", sa.JSON(), nullable=False, server_default="{}"))
    op.add_column("models", sa.Column("blind_result", sa.JSON(), nullable=True))
    op.create_foreign_key(None, "models", "datasets", ["dataset_id"], ["id"])
    op.add_column(
        "uploaded_files",
        sa.Column("source", sa.String(length=16), nullable=False, server_default="upload"),
    )
    op.add_column("uploaded_files", sa.Column("rel_path", sa.String(length=512), nullable=True))
    op.add_column(
        "uploaded_files", sa.Column("version", sa.Integer(), nullable=False, server_default="1")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploaded_files", "version")
    op.drop_column("uploaded_files", "rel_path")
    op.drop_column("uploaded_files", "source")
    op.drop_constraint(None, "models", type_="foreignkey")
    op.drop_column("models", "blind_result")
    op.drop_column("models", "comparison")
    op.drop_column("models", "dataset_id")
    op.drop_index(op.f("ix_prediction_evaluations_well_id"), table_name="prediction_evaluations")
    op.drop_table("prediction_evaluations")
    op.drop_table("well_quality")
    op.drop_index(op.f("ix_quality_reviews_well_id"), table_name="quality_reviews")
    op.drop_table("quality_reviews")
    op.drop_table("limits")
    op.drop_table("datasets")
    op.drop_table("scan_runs")
    op.drop_table("blind_sets")
    # ### end Alembic commands ###
