"""purpose training monitoring

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 07:18:49.736398
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploaded_files",
        sa.Column("purpose", sa.String(length=16), nullable=False, server_default="training"),
    )
    op.add_column(
        "wells",
        sa.Column("purpose", sa.String(length=16), nullable=False, server_default="training"),
    )
    op.drop_constraint("uq_well_name_section", "wells", type_="unique")
    op.create_index(op.f("ix_wells_purpose"), "wells", ["purpose"], unique=False)
    op.create_unique_constraint(
        "uq_well_name_section_purpose", "wells", ["name", "section_in", "purpose"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_well_name_section_purpose", "wells", type_="unique")
    op.drop_index(op.f("ix_wells_purpose"), table_name="wells")
    op.create_unique_constraint(
        "uq_well_name_section", "wells", ["name", "section_in"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("wells", "purpose")
    op.drop_column("uploaded_files", "purpose")
    # ### end Alembic commands ###
